version: '3'

services: 

   mongo: 
      image: 'mongo:latest'
      restart: always
      volumes:
         - ./bamdealist-backup:/usr/src/backup
         - mongodb:/data/db
         - mongodb_config:/data/configdb

   web:
      image: 'node:latest' 
      # build: ./docker
      # restart: always
      working_dir: /usr/src/app
      command: node src/server/server
      depends_on: 
         - 'mongo'
      environment: 
         - MONGO_HOST=mongo
         - MONGO_DATABASE=bamdealist
         - NODE_ENV=production
         - INTERNAL_APP_PORT
         - EXTERNAL_PROTOCOL
         - EXTERNAL_HOSTNAME
         - EXTERNAL_BIND_PORT
         - SESSION_SECRET
         - GOOGLE_OAUTH_CLIENT_ID
         - GOOGLE_OAUTH_CLIENT_SECRET
      ports: 
         - '${EXTERNAL_BIND_PORT}:${INTERNAL_APP_PORT}' # note that we are doing localhost only here via port expose - will only want that for dev
      volumes:
         - ./:/usr/src/app
         - ./bamdealist-backup:/usr/src/backup

# persistent volume for mongo data so we don't lose content on restart
volumes:
  mongodb:
  mongodb_config: